import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import { UserProvider } from "@/context/UserContext";
import { SessionProvider } from "next-auth/react";
import LogoutButton from "@/components/navbar/LogoutButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={inter.className}>
          <LogoutButton />
          <div>{children}</div>
        </body>
      </UserProvider>
    </html>
  );
}
