import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Rajdhani } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/context/UserContext";
import { GlobalProvider } from "@/context/GlobalContext";

const rajdhani = Rajdhani({ weight: "500", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GlobalProvider>
        <UserProvider>
          <body className={rajdhani.className}>
            <div>{children}</div>
          </body>
        </UserProvider>
      </GlobalProvider>
    </html>
  );
}
